FROM node:lts-jessie

ENV INSTALL_PATH /app

RUN mkdir -p $INSTALL_PATH

WORKDIR $INSTALL_PATH

COPY . .

RUN npm install && npm run build

FROM nginx:stable

RUN mkdir -p /static

COPY ./wait-for.sh  /bin/wait-for
COPY ./entrypoint.sh /entrypoint.sh
COPY ./nginx.tmpl /etc/nginx/nginx.tmpl

COPY --from=0 /app/dist /static

ENTRYPOINT /entrypoint.sh