version: '3.3'

networks:
  proxy:
    external:
      name: proxy
  app:

volumes:
  dbdata:

services:
  nginx:
    image: "${REGISTRY_HOST}/${PROJECT_IMAGE}/nginx:${PROJECT_TAG}"
    networks:
      - app
      - proxy
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      PROJECT_NAME: ${PROJECT_NAME}
      VUE_APP_WEB_PUSH_VAPID_PUBLIC_KEY: ${VUE_APP_WEB_PUSH_VAPID_PUBLIC_KEY}
    deploy:
      replicas: 1
      labels:
        traefik.port: 80
        traefik.docker.network: proxy
        traefik.backend: "${PROJECT_NAME}_nginx"
        traefik.frontend.rule: "Host:${VIRTUAL_HOST}"
        traefik.acme.domains: "${VIRTUAL_HOST}"
        traefik.frontend.headers.SSLRedirect: 'true'
      placement:
        constraints:
          - node.labels.role == ${TARGET_NODE}

  db:
    image: postgres:9.6
    networks:
      - app
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - dbdata:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == ${TARGET_NODE}

  app:
    image: "${REGISTRY_HOST}/${PROJECT_IMAGE}/app:${PROJECT_TAG}"
    networks:
      - app
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      SESSION_SECRET: ${SESSION_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      WEB_PUSH_VAPID_PUBLIC_KEY: ${WEB_PUSH_VAPID_PUBLIC_KEY}
      WEB_PUSH_VAPID_PRIVATE_KEY: ${WEB_PUSH_VAPID_PRIVATE_KEY}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == ${TARGET_NODE}
