version: '3'
services:
  frontend:
    build:
      context: ./frontend
    command: npm run serve
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - app

  app:
    build:
      context: ./app
    command: npm run dev
    env_file:
      - .env
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./tmp/db:/var/lib/postgresql/data